name: Test

run-name: ${{ github.triggering_actor }} has triggered unittests

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      - name: Install dependencies
        run: npm ci

      - name: Test 🧪
        run: npm run test
  
      - name: Publish Results Badge
        uses: wjervis7/vitest-badge-action@v1.0.0
        if: success() || failure() # run whether steps succeed or not
        with:
          result-type: statements
          upload-badge: false

      - name: Commit data
        run: |
          mv ./badge.svg docs/coverage.svg
          if git diff docs/*.svg | grep . > /dev/null ; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git pull
            git add docs/*.svg
            git commit -m "update badge"
            git push
          fi